### ISSUE TITLE
Time-out actions have no default operation

### ISSUE THREAD

**Issue by yu36yuqing** [jenkinsci/build-timeout-plugin#60]
When we use this plugin, we need to set the "Time-out actions" manually, otherwise the plugin will never trigger any operation. 
But according the description "Abort the build. This is a default operation performed if no operations are specified. ", it should be no need to set the item manually, but always has a default value "Abort the build".
So, the problem is that if we don`t set the "Time-out actions" into "Abort the build" manually, the job will never be aborted on time.
I don`t know, if I create an issue here, is there someone will answer it? Or there are some other websites to raise an issue?

**Comment by ikedam** [comment]
Jenkins plugins JIRA for its bug tracking. Please create a JIRA ticket instead.
https://issues.jenkins-ci.org/issues/?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20'build-timeout-plugin'
(I found the link in the wiki page is dead. I'll fix that)

That issue sounds the one already fixed in build-timeout 1.14.1.
Please also report details of your environment such as versions of the plugin, Jenkins, Java, and so on.

**Comment by yu36yuqing** [comment]
Thanks for your quickly answer.
I have a fast view about some related fixed issues but didn`t find the same issue, maybe I miss it by chance.
I will create a new issue on that website after I get the basic info of the plugin.
Thanks~

**Comment by yu36yuqing** [comment]
Hi, when I try to create a new acccount for myself, there is no captcha for me and I cannt move on to create an issue.
I have tried both IE and Firefox, all failed.
URL is https://accounts.jenkins.io/signup.

BTW, I have got the version info:
** Jenkins version: 1.570
** build timeout plugin 1.14
** Jdk 1.5.07

Could you help to check if this problems was fixed after version 1.14 ?
Thanks in advance~

**Comment by ikedam** [comment]
Have a look at the Wiki page. https://wiki.jenkins-ci.org/display/JENKINS/Build-timeout+Plugin
Anyway, no supports for old versions.
